services:
  - type: web
    name: homebuddy-backend
    env: java
    runtime: java21
    buildCommand: |
      #!/bin/bash
      # Make mvnw executable
      chmod +x mvnw
      # Set JAVA_HOME
      export JAVA_HOME=/opt/render/project/src/.jdk
      export PATH=$JAVA_HOME/bin:$PATH
      # Build the application
      ./mvnw clean package -DskipTests
    startCommand: java -jar target/*.jar
    envVars:
      - key: JAVA_HOME
        value: /opt/render/project/src/.jdk
      - key: PATH
        value: /opt/render/project/src/.jdk/bin:$PATH
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: PORT
        value: 8080
      - key: CORS_ALLOWED_ORIGINS
        value: https://homebuddy-hazel.vercel.app
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRATION
        value: 86400000
      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://dpg-d02cnljuibrs73aof880-a.oregon-postgres.render.com:5432/homebuddydb
      - key: SPRING_DATASOURCE_USERNAME
        value: homebuddydb_user
      - key: SPRING_DATASOURCE_PASSWORD
        value: 6PbcYOXQtKkAjSGiDr2lllH4hONSlkTx 