services:
  - type: web
    name: homebuddy-backend
    env: docker
    dockerfilePath: ./Dockerfile
    dockerCommand: java -jar target/*.jar
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: PORT
        value: 8080
      - key: CORS_ALLOWED_ORIGINS
        value: https://homebuddy-hazel.vercel.app
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRATION
        value: 86400000
      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://dpg-d02cnljuibrs73aof880-a.oregon-postgres.render.com:5432/homebuddydb
      - key: SPRING_DATASOURCE_USERNAME
        value: homebuddydb_user
      - key: SPRING_DATASOURCE_PASSWORD
        value: 6PbcYOXQtKkAjSGiDr2lllH4hONSlkTx
      - key: SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE
        value: 5
      - key: SPRING_DATASOURCE_HIKARI_MINIMUM_IDLE
        value: 1 